export type DomainErrorCode =
  | 'MCP_ENDPOINT_INVALID'
  | 'MCP_SERVER_ID_REQUIRED'
  | 'MCP_SERVER_NAME_REQUIRED'
  | 'MCP_TOOL_NAME_REQUIRED'
  | 'MCP_TOOL_ENHANCEMENT_INVALID'
  | 'MCP_TOOL_REVISION_INVALID'
  | 'MEMORY_CONFIDENCE_INVALID'
  | 'MEMORY_ID_REQUIRED'
  | 'MEMORY_SOURCE_REQUIRED'
  | 'MEMORY_SUMMARY_REQUIRED'
  | 'CONTEXT_ID_REQUIRED'
  | 'GOAL_CONTEXT_MISMATCH'
  | 'GOAL_ID_REQUIRED'
  | 'GOAL_VERSION_INVALID'
  | 'SKILL_DRAFT_ID_REQUIRED'
  | 'SKILL_DESCRIPTION_REQUIRED'
  | 'SKILL_ENABLE_REQUIRES_VALIDATION'
  | 'SKILL_ID_REQUIRED'
  | 'SKILL_RELATION_ID_REQUIRED'
  | 'SKILL_RELATION_SELF_REFERENCE'
  | 'SKILL_RUNTIME_POLICY_INVALID'
  | 'SKILL_TOOL_POLICY_OVERLAP'
  | 'SKILL_VERSION_INVALID'
  | 'TASK_ID_REQUIRED'
  | 'TASK_WAIT_TIMEOUT_INVALID'
  | 'TEMPORARY_SKILL_ALREADY_EXPIRED'
  | 'TEMPORARY_SKILL_DESCRIPTION_REQUIRED'
  | 'TEMPORARY_SKILL_EXPIRY_INVALID'
  | 'TEMPORARY_SKILL_ID_REQUIRED'
  | 'TEMPORARY_SKILL_TOOL_REQUIRED'
  | 'TASK_PHASE_TRANSITION_INVALID'
  | 'TASK_TERMINAL_MUTATION_FORBIDDEN'
  | 'USER_ID_INVALID'
  | 'WORKFLOW_PLAN_ID_REQUIRED';

export class DomainError extends Error {
  readonly code: DomainErrorCode;
  readonly details: Readonly<Record<string, string>>;

  constructor(
    code: DomainErrorCode,
    message: string,
    details: Readonly<Record<string, string>> = {},
  ) {
    super(message);
    this.name = 'DomainError';
    this.code = code;
    this.details = details;
  }
}
