import { DomainError } from '../errors.js';

export type ArtifactDomainErrorCode =
  | 'ARTIFACT_INVALID'
  | 'ARTIFACT_DEFINITION_MISMATCH'
  | 'ARTIFACT_CONDITION_INVALID'
  | 'ARTIFACT_JSON_INVALID'
  | 'ARTIFACT_LIFECYCLE_TRANSITION_INVALID'
  | 'ARTIFACT_ACTIVATION_EVIDENCE_REQUIRED'
  | 'ARTIFACT_LINEAGE_INVALID'
  | 'ARTIFACT_RUNTIME_BINDING_INVALID'
  | 'EXPERIENCE_TRACE_INVALID'
  | 'EXPERIENCE_TRACE_EVENT_INVALID'
  | 'COHORT_DEFINITION_INVALID'
  | 'PROCESS_VARIANT_INVALID'
  | 'DISCOVERED_PROCESS_PATTERN_INVALID'
  | 'WORKFLOW_PATTERN_INVALID'
  | 'EXPERIENCE_COMPILATION_ID_INVALID'
  | 'EXPERIENCE_COMPILATION_HASH_INVALID'
  | 'EXPERIENCE_COMPILATION_TIMESTAMP_INVALID'
  | 'EXPERIENCE_COMPILATION_NUMBER_INVALID'
  | 'EXPERIENCE_COMPILATION_VERSION_INVALID'
  | 'EXPERIENCE_COMPILATION_JSON_INVALID'
  | 'EXPERIENCE_COMPILATION_BOUND_EXCEEDED'
  | 'EXPERIENCE_COMPILATION_DUPLICATE';

export class ArtifactDomainError extends DomainError {
  constructor(
    code: ArtifactDomainErrorCode,
    message: string,
    details: Readonly<Record<string, string>> = {},
  ) {
    super(code, message, details);
    this.name = 'ArtifactDomainError';
  }
}
